### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by glennsl** [reasonml-old/bs-containers#2]
- [ ] Use `camelCase` instead of `snake_case`
- [ ] Get rid of scary monadic and math-y terminology
- [ ] Follow the conventions used in the `Js.*` modules
- [ ] Type functions correctly, e.g. `compare` should return a proper variant, not `0`, `1` or `-1`
- [ ] Remove operators and aliases, e.g. `pure` as an alias for `return`
- [ ] Remove the use of exceptions for internal logic (maybe? seems very sketchy to me but perhaps there's a really really good reason, see [this example](https://github.com/BuckleTypes/bs-containers/blob/master/src/bopt.ml#L163))
- [ ] Replace `Format.printf` calls, they pull in a lot stuff for little benefit
- [ ] Move the `Option` and `Result` modules to the BuckleScript std lib as soon as possible, others may come later
- [ ] Document everything properly, with examples
- [ ] Add tests for everything
- [ ] Alias and eventually replace functions from corresponding std lib modules

**Comment by glennsl** [comment]
The above is just my 2 cents to start off with, of course, and I'll update the list according to what we agree on. But you might notice a trend og moving away from OCaml conventions and interop towards JS conventions and interop.

cc @bobzhang @chenglou @mransan

**Comment by bobzhang** [comment]
this looks good to me, `compare` return an int is quite common though.
also utilities around sexp is not necessary

**Comment by glennsl** [comment]
Is all the sequence stuff just for sexps?

> return an int is quite common though
I know, but it's so terrible! I don't understand why the OCaml community don't just bite the bullet and make the jump once and for all. It'll be like ripping off a bandaid, painful at first but over in an instant. But you'll be rewarded with both readable code and exhaustiveness checking.

But to be fair, I probably have an irrational angst about these things

**Comment by dorafmon** [comment]
I can start with writing some unit tests and get this repo working with travis.

**Comment by chenglou** [comment]
I agree with every point here! =D

Though I'm unsure about moving option/result into BS stdlib. Code written using the current stdlib compile to both JS and native correctly. I'd rather them stay in Containers (and it'll be a nice attraction).

**Comment by mransan** [comment]
Very good points. 

I think operators are useful but only in an Infix module. For instance in `bopt` I would remove all the operators at the top level but keep the Infix module. This allows to do thing like:

```OCaml
let f a b c = 
  (* .. *) 
  let x = 
    let open Bopt.Infix in 
    y >>= (fun x -> (* ... *) Some y) >>= (fun y -> (* ... *) Some z) 
  in
```

**Comment by glennsl** [comment]
@chenglou I just think it's unnecessary that even the tiniest FFI library should have a dependency on all of bs-containers just to deal with an `option`. But I'd want them to be clearly separate from the OCaml std lib, perhaps as `Bs.Option`? Would that ease your concern?

@mransan I certainly see the allure of having operators, but it's also extremely hostile to newcomers. I'd like to discourage, or at least not encourage, library authors to use cryptic operators. I think ithey're fine to use in your own projects, and it would be nice to have them standardized, but maybe they're so culturally entrenched that they don't need to be defined centrally. Perhaps you could just as well define them in your own projects yourself? I'm not sure, but there needs to be a good balance here, and I'd rather the scale tips in favor of being friendly to newcomers.

**Comment by mransan** [comment]
@glennsl I agree operators should not be the main interface. For instance in the bopt module, there are no bind function but rather the commonly used bind operator. I agree this is not welcoming to new comers. I would rather have the bind function in the top level module, and an Infix sub module with the operator which are just aliases to the function names. 

```OCaml
type 'a t 

val bind : 'a t -> ('a -> 'b t) -> 'b t 

val map : 'a t -> ('a -> 'b) -> 'b t 

(* ... keep adding all the other functions ... *)

module Infix : sig 
  val (>>=) :  'a t -> ('a -> 'b t) -> 'b t 
  val (>|=) :   'a t -> ('a -> 'b) -> 'b t 
end
```

Of course in the first place, we could simply omit the Infix module but it's quite a common style in the FP community and having them in a sub module at the end of the file, doesn't make it the primary interface.

**Comment by glennsl** [comment]
But they will be scared away if the example code they see do use it. The question is, does having them contained in an Infix module communicate the intent well enough? I'm ok with keeping it in for now and revisitng removal later if it becomes a problem, if you guys think that's better than removing now and perhaps adding it back later.

**Comment by mransan** [comment]
I think the examples should focus on the main functions not those operators. The only documentation they require is for which function they are an alias to:
```
val bind : 'a t -> ('a -> 'b t) -> 'b t 
(** ... 
 @example {[
]} *)

(*.. *) 

module Infix : sig 
  val (>>=) : 'a -> ('a -> 'b t) -> 'b t 
  (** alias for bind *)
end

**Comment by glennsl** [comment]
I'm not concerned about the example code we do control. I'm concerned that it would encourage their use in example code we do not control. The examples in the blog posts written and posted to HN to advocate the ecosystem, and in the description and documentation of all the other libraries in the ecosystem.

Look at what happened with Scala and Scalaz. People practically ran away from the language and ecosystem when seeing that kind of code.

**Comment by mransan** [comment]
I understand your concern and I think it's much easier to add this submodule in the future than to remove it so I would rather not include it for now. 

I haven't followed the scala/scalaz community, I think the OCaml community has shown self constrained when it comes to operator, (bind/map are now fairly standard,  +/-/*... when used are clear). Better be cautious and add them with carefully in the future.

**Comment by chenglou** [comment]
cc @bordoley; we can take the occasion to remove some overlaps from containers/Immutable-re.

**Comment by bordoley** [comment]
Here is the subset of the Immutable.re api that is most relevant to this conversation: https://gist.github.com/bordoley/a0dabd0117f70781422bf66c9a12ca9b

The library includes both lazy pull based monadic sequences, internally implemented as:
```
type iterator 'a =
  | Next 'a (t 'a)
  | Completed

and t 'a = unit => iterator 'a;
```

as well as much more efficient Iterators, built upon reducer functions with a while test:
```
type t 'a = {
  reduce: 'acc . ('acc => 'a => bool) => ('acc => 'a => 'acc) => 'acc => 'acc,
};
```
Immutable.re also includes collection like APIs for Options and Lists, but intentionally does not including bind/map operators (though I have them internally).

**Comment by dorafmon** [comment]
@chenglou @bordoley sure, I am cleaning up the repo and refactoring it to align with the Roadmap. will cc you guys for a review when I submit a PR. As for infix operators let's go over them case by case, if it is common and simple enough we keep them, if not we move them away from the interface.

**Comment by mransan** [comment]
I think one interesting design decision @bordoley code raises is whether or not we go down the road of defining numerous small module signatures for things like Iteratable/Reducable/Monadic/... and then include those signature in module like Array/List/Option. The module Option at the end of Dave's gist is a good example. 

This approach was heavily used by Jane Street core but not by container library. 

If we target easy to understand interfaces for OCaml beginners then it might not be ideal to employ this technique. We could limit the use of those signatures to functor input for which they are crucial.

**Comment by chenglou** [comment]
Beginner-friendly please! We'll have plenty of chances of playing with sophisticated features once we succeed =)

**Comment by glennsl** [comment]
I'd love such "interfaces". It makes total sense to me, and I think it would actually be more beginner-friendly for people coming from statically typed OO-languages, who understand interfaces well. And it should be very familiar to clojurists and people coming from most statically typed FP-languages. Not sure about JS devs though.

@chenglou Is there some specific case(s) that have you concerned?

**Comment by chenglou** [comment]
Nah, no strong opinion beside making sure it stays beginner-friendly

**Comment by mransan** [comment]
Well that was not my intention to promote it :) Here are a few concern:
* **Documentation tool**: are they good support for it? (ie do you see the resulting signature)
* **Reading code**: very hard to know all the method defined on a module, you basically have to browse the multiple signature files that are included... and it takes a long time to be familiar with all of them. 
* **Decoupling**: The major difference with OO and Modules is the complete decoupling of the implementation vs the interface. In OO you are forced to implement an interface to plug your code into another library. With Module either you actually implement the module interface without including it, or you just do a small inline module when calling a functor.
* **Hard to design right**: Let's say you define a module signature X which is included in 5 modules of your library. What if you want to a function to X but does not make sense for one of the 5 ... then you end up with OO nightmare.

**Comment by glennsl** [comment]
For documentation, we can "expand" the includes of the modules we expose. I think that would address you "Reading code" point as well, if I understand you correctly.

For the latter two points, I would need to see some actual implementation to really understand it I think. But these seem to apply more to the design of applications that continuously evolve than it does to a comparatively well-defined library. I understand that this will make it harder to design and implement it, but this would only have to be done once, and the added constraints will likely (hopefully) result in a more coherent and well-designed library. Even if those constrains are rather superficial.

**Comment by bordoley** [comment]
Re: Module signatures, Immutable.re uses them primarily for "documentation" (ala java and C# interfaces) and is not heavily functorized. The use of module signatures allowed me to define the different capabilities of a collection using common documentation. If only ocaml doc would generate useful inline api docs.

**Comment by chenglou** [comment]
@glennsl there's no include in an interface file? It's all statically resolved already

**Comment by mransan** [comment]
While the documentation can be worked out, things like github will still require reading multiple files to understand a module. Furthermore the documentation might be different depending on which module this signature is included... for instance documenting the complexity of an algorithm. In the example below an `at` function might either be constant time or linear depending if it's a list or an array.

Here is an example of how imposing module signature can be tricky. 

Let's say we want to introduce the HasIndex for all container which can access element given an index. 
```OCaml
module type HasIndex = sig 
  type 'a t 
  val at : 'a t -> int -> 'a 
end 
```OCaml

Related to the documentation issue about the performance, the name `at` for a list might not be the best name. I actually like the `List.nth` name because explain better the complexity of the operation.

Then we want to add `first` and `last` to this module which are commonly used indices 

```OCaml
module type HasIndex = sig 
  type 'a t 
  val at : 'a t -> int -> 'a 
  val first : 'a t -> 'a 
  val last : 'a t -> 'a
end 
```

This all works fine for array/list/.. But now let's say we want to add a perpetual list (for instance with a continuation function where the next element is a function of the previous one). The functions`at` and `first` makes sense but `last` doesn't. One can argue that `last` should be in a new module called `BoundedLength` which contains both `length` and `last` (and true it is a better design). This kind of design is very difficult and I usually like to assume that I will get them wrong :). 

How do we define the scope of those module signatures? If they only contain one function then they have very limited purpose, if they contain many then we increase the chance of designing wrong. 

Sharing module signature for Functor input is usually easier because the design of such modules signature is driven by what the Functor needs, not by a library design which aims at grouping functions into sets.

Sorry for the lengthy example :) Maybe we could start without this signature design first and gradually add them if we feel the need. Adding is backward compatible while removing/modifying won't be.

**Comment by mransan** [comment]
Other topic of discussion for a standard library that we should setup some guideline for:

**Label arguments**, should we:
* have an interface with and without like `String` and `StringLabels`
* always|never have them, have them only when the type is not explicit enough (like string/int ..)

**Argument order**
```OCaml
val f : b -> 'a t -> 'a t (* Favor piping |> *)
(* or *)
val f : 'a t -> b -> 'a t (* Make the main type first *)
```

**Comment by mransan** [comment]
**Exception as returned type** (not used in control flow of the implementation) 

* Should we discourage the use of exception and solely use `Result | Some | None`
* Should we provide 2 implementations of the same function when performance could be critical exceptionality hard to anticipate. (For example one could have a use case where an element not present in the container is an exception, not really a search).

```OCaml
val : find -> ('a, 'b) t -> 'a -> 'b option
val : find_exn -> ('a, 'b) -> 'a -> 'b 
```

**Comment by chenglou** [comment]
Not too many exception throwing code in stdlib please. But if we really need some, I propose find_raises for clarity

**Comment by mransan** [comment]
@chenglou I agree,  I usually only appreciate having both when you cannot predict how exceptional the error case is. Mostly things like:
* container access
* decoding
* search

**Comment by glennsl** [comment]
I don't have strong opinions on this, and will have to just see what works, bu my current inclinations is:
- Labels only to disambiguate
- Piped argument order
- Use exceptions only when truly exceptional, prefer safe abstractions for performance where possible

@mransan re: interfaces. I have to see how this is actually implemented in Immutable.re to understand it properly, but the idea is to only implement interfaces that are well-defined, intuitive and widely familiar. We're not talking about OO-style DRY-sickness. The purpose is to encode formal relationship between the data structures in order to constrain them to conform to them and to help users understand them. But not at the cost of more difficult overview of any single data structure. So I guess the bottom line is, I agree we should wait :)

**Comment by glennsl** [comment]
I added an additional point to the roadmap:
- [ ] Alias and eventually replace functions from corresponding std lib modules
